### ISSUE TITLE
Spacing Issues

### ISSUE THREAD

**Issue by erncat-zz** [erncat-zz/dsn1676-assignment-5#1]
When making my browser larger, my button and input stretch away from each other. Can;t figure out how to keep everything the same size. 

@thomasjbradley

**Comment by erncat-zz** [comment]
![screen shot 2015-03-02 at 1 30 59 pm](https://cloud.githubusercontent.com/assets/6340268/6447450/7530a47e-c0e0-11e4-8ad1-d75c8b37c2df.png)
![screen shot 2015-03-02 at 1 31 07 pm](https://cloud.githubusercontent.com/assets/6340268/6447449/75301be4-c0e0-11e4-9791-30ce5448876e.png)

**Comment by thomasjbradley** [comment]
Should their widths be set in percents maybe?
